=== supreethavadhani/Java-metadev-server-example/assets/schema/app.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Schema for application.json",
    "required": [
        "name",
        "dataTypes"
    ],
    "additionalProperties": false,
    "properties": {
        "name": {
            "type": "string"
        },
        "tenantFieldName": {
            "type": "string"
        },
        "tenantDbName": {
            "type": "string"
        },
        "dataTypes": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "textTypes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "required": [
                            "maxLength"
                        ],
                        "properties": {
                            "errorId": {
                                "type": "string"
                            },
                            "regex": {
                                "type": "string"
                            },
                            "mnLength": {
                                "type": "integer"
                            },
                            "maxLength": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "integerTypes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "required": [
                            "maxValue"
                        ],
                        "properties": {
                            "errorId": {
                                "type": "string"
                            },
                            "mnValue": {
                                "type": "integer"
                            },
                            "maxValue": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "decimalTypes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "required": [
                            "maxValue",
                            "nbrFractions"
                        ],
                        "properties": {
                            "errorId": {
                                "type": "string"
                            },
                            "mnValue": {
                                "type": "integer"
                            },
                            "maxValue": {
                                "type": "integer"
                            },
                            "nbrFractions": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "booleanTypes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "properties": {
                            "errorId": {
                                "type": "string"
                            }
                        }
                    }
                },
                "dateTypes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "required": [
                            "maxPastDays",
                            "maxFutureDays"
                        ],
                        "properties": {
                            "errorId": {
                                "type": "string"
                            },
                            "maxPastDays": {
                                "type": "integer"
                            },
                            "maxFutureDays": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "timestampTypes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "properties": {
                            "errorId": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "valueLists": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "value",
                        "label"
                    ],
                    "properties": {
                        "value": {
                            "type": [
                                "string",
                                "integer"
                            ]
                        },
                        "label": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                }
            }
        },
        "keyedLists": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "value",
                            "label"
                        ],
                        "properties": {
                            "value": {
                                "type": [
                                    "string",
                                    "integer"
                                ]
                            },
                            "label": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            }
        },
        "runtimeLists": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "dbTableName",
                    "dbColumn1",
                    "dbColumn2"
                ],
                "properties": {
                    "dbTableName": {
                        "type": "string"
                    },
                    "dbColumn1": {
                        "type": "string"
                    },
                    "dbColumn2": {
                        "type": "string"
                    },
                    "keyColumn": {
                        "type": "string"
                    },
                    "tenantColumn": {
                        "type": "string"
                    },
                    "activeColumn": {
                        "type": "string"
                    },
                    "keyIsNumeric": {
                        "type": "boolean"
                    },
                    "valueIsNumeric": {
                        "type": "boolean"
                    },
                    "parentTable": {
                        "type": "string"
                    },
                    "parentIdColumnName": {
                        "type": "string"
                    },
                    "parentNameColumnName": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        }
    }
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/application.json
{
    "name": "metadev-example",
    "tenantFieldName": "tenentId",
    "tenantDbName": "tenent_id",
    "runtimeLists": {
        
    },
    "dataTypes": {
        "booleanTypes": {
            "bool": {
                "errorId": "invalidBool"
            }
        },
        "decimalTypes": {
            "grade": {
                "errorId": "invalidGrade",
                "maxValue": 100,
                "nbrFractions": 2
            },
            "internalMarks": {
                "errorId": "invalidIternalMarks",
                "maxValue": 100,
                "nbrFractions": 2
            },
            "decimal": {
                "errorId": "invalidDecimal",
                "maxValue": 1000,
                "nbrFractions": 4
            }
        },
        "dateTypes": {
            "date": {
                "errorId": "invalidDate",
                "maxPastDays": 73000,
                "maxFutureDays": 73000
            }
        },
        "integerTypes": {
            "country": {
                "errorId": "invalidCountry",
                "maxValue": 999
            },
            "flexibleId": {
                "errorId": "invalidFlexibleId",
                "minValue": -1,
                "maxValue": 9999999999999
            },
            "id": {
                "errorId": "invalidId",
                "maxValue": 9999999999999
            },
            "integer": {
                "errorId": "invalidInteger",
                "minVlue": -99999999999,
                "maxValue": 9999999999999
            },
            "income": {
                "errorId": "invalidIncome",
                "minVlue": 0,
                "maxValue": 9999999999999
            },
            "tenantKey": {
                "errorId": "invalidTenentKey",
                "maxValue": 9999999999999
            },
            "marks": {
                "errorId": "invalidMraks",
                "minVlue": 0,
                "maxValue": 100
            },
            "valuationType": {
                "errorId": "invalidValuationType",
                "minVlue": 1,
                "maxValue": 3
            }
        },
        "textTypes": {
            "accountStatus": {
                "errorId": "invalidAccountStatus",
                "maxLength": 10
            },
            "code": {
                "errorId": "invalidCode",
                "maxLength": 50
            },
            "desc": {
                "errorId": "invalidDesc",
                "maxLength": 1000
            },
            "email": {
                "errorId": "invalidEmail",
                "maxLength": 1000
            },
            "gender": {
                "errorId": "invalidGender",
                "maxLength": 10
            },
            "govtCode": {
                "errorId": "invalidGovtCode",
                "maxLength": 50
            },
            "ip": {
                "errorId": "invalidIp",
                "maxLength": 1000
            },
            "json": {
                "errorId": "invalidJson",
                "maxLength": 10000
            },
            "loginId": {
                "errorId": "invalidLoginId",
                "maxLength": 50
            },
            "marksOrAb": {
                "errorId": "invalidMarksOrAb",
                "mnLength": 1,
                "maxLength": 5,
                "regex": "(ab|AB|Ab|\\d{0,2}\\.?\\d{0,2})"
            },
            "ppOrNp":{
                "errorId": "invalidMarksOrAb",
                "mnLength": 1,
                "maxLength": 5,
                "regex": "(pp|Pp|PP|pP|np|Np|nP|NP|^$)"
            },
            "name": {
                "errorId": "invalidName",
                "maxLength": 150
            },
            "phone": {
                "errorId": "invalidPhone",
                "maxLength": 12,
                "minLength": 10,
                "regex": "[1-9][0-9]*"
            },
            "pin": {
                "errorId": "invalidPin",
                "minLength": 6,
                "maxLength": 6,
                "regex": "[1-9][0-9]{5}"
            },
            "state": {
                "errorId": "invalidState",
                "maxLength": 50
            },
            "text": {
                "errorId": "invalidText",
                "maxLength": 1000
            },
            "uniqueId": {
                "errorId": "invalidUniqueId",
                "regex": "[1-9][0-9]{15}",
                "minLength": 16,
                "maxLength": 16
            },
            "url": {
                "errorId": "invalidUrl",
                "maxLength": 1000
            },
            "userType": {
                "errorId": "invalidUserType",
                "maxLength": 20
            }
        },
        "timestampTypes": {
            "timestamp": {
                "errorId": "invalidTimestamp"
            }
        }
    },
    "valueLists": {
        "accountStatus": [{
                "value": "Active",
                "label": "Active"
            },
            {
                "value": "Suspended",
                "label": "Suspended"
            },
            {
                "value": "Closed",
                "label": "Closed"
            }
        ],
        "userType": [{
                "value": "student",
                "label": "student"
            },
            {
                "value": "staff",
                "label": "staff"
            },
            {
                "value": "admin",
                "label": "admin"
            },
            {
                "value": "guardian",
                "label": "guardian"
            },
            {
                "value": "trustee",
                "label": "trustee"
            }
        ],
        "instituteType": [{
                "value": "DSERTPS",
                "label": "Karnataka State Syllabus Primary School"
            },
            {
                "value": "DSERTPHS",
                "label": "Karnataka State Syllabus Higher School"
            },
            {
                "value": "CBSE ",
                "label": "CBSE"
            },
            {
                "value": "ENG_A_VTU",
                "label": "Engineering College (Automonus Under VTU)"
            },
            {
                "value": "ENG_VTU",
                "label": "Engineering College ( VTU)"
            }
        ],
        "admissionQuota": [{
                "value": "CET",
                "label": "CET"
            },
            {
                "value": "COMEDK",
                "label": "COMEDK"
            },
            {
                "value": "CETSNQ",
                "label": "CET-SNQ"
            },
            {
                "value": "MANG",
                "label": "MANAGEMENT"
            },
            {
                "value": "ICD",
                "label": "ICD"
            },
            {
                "value": "NRI",
                "label": "NRI"
            },
            {
                "value": "GOI",
                "label": "GOI"
            },
            {
                "value": "Other",
                "label": "Other"
            }
        ],
        "religion": [{
                "value": "Hindu",
                "label": "Hindu"
            },
            {
                "value": "Muslim",
                "label": "Muslim"
            },
            {
                "value": "Christian",
                "label": "Christian"
            },
            {
                "value": "Sikh",
                "label": "Sikh"
            },
            {
                "value": "Jain",
                "label": "Jain"
            },
            {
                "value": "Others",
                "label": "Other"
            }
        ],
        "relationType": [{
                "value": "Mother",
                "label": "Mother"
            },
            {
                "value": "Father",
                "label": "Father"
            },
            {
                "value": "Legal Guardian",
                "label": "Legal Guardian"
            }
        ],
        "documentType": [{
                "value": "Marks Card",
                "label": "Marks Card"
            },
            {
                "value": "Certificate",
                "label": "Ceritifcate (e.g: Birth Certificate etc)"
            },
            {
                "value": "Photo",
                "label": "Photo"
            },
            {
                "value": "Govt Id",
                "label": "Govt Id(e.g.: Passport, DL etc)"
            }
        ],
        "domicileState": [{
                "value": "Karnataka",
                "label": "Karnataka"
            },
            {
                "value": "Non-Karnataka",
                "label": "Non-Karnataka"
            },
            {
                "value": "Foreign",
                "label": "Foreign"
            }
        ],
        "gender": [{
                "value": "Male",
                "label": "Male"
            },
            {
                "value": "Female",
                "label": "Female"
            },
            {
                "value": "Others",
                "label": "Others"
            },
            {
                "value": "Not Applicable",
                "label": "Not Applicable"
            }
        ],
        "bloodGroup": [{
                "value": "O -ve",
                "label": "O -ve"
            },
            {
                "value": "O +ve",
                "label": "O +ve"
            },
            {
                "value": "A -ve",
                "label": "A -ve"
            },
            {
                "value": "A +ve",
                "label": "A +ve"
            },
            {
                "value": "B -ve",
                "label": "B -ve"
            },
            {
                "value": "B +ve",
                "label": "B +ve"
            },
            {
