=== supreethavadhani/Java-metadev-server-example/assets/schema/record.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Schema for record. file type *.rec.json",
    "required": [
        "name",
        "fields"
    ],
    "additionalProperties": false,
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "nameInDb": {
            "type": "string"
        },
        "customValidation": {
            "type": "string"
        },
        "useTimestampCheck": {
            "type": "boolean"
        },
        "operations": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "get",
                    "create",
                    "update",
                    "filter",
                    "delete"
                ]
            }
        },
        "fields": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "dataType"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "dataType": {
                        "type": "string",
                        "enum": [
                            "accountStatus",
                            "bool",
                            "code",
                            "country",
                            "date",
                            "desc",
                            "email",
                            "flexibleId",
                            "govtCode",
                            "id",
                            "ip",
                            "json",
                            "loginId",
                            "money",
                            "name",
                            "integer",
                            "phone",
                            "pin",
                            "state",
                            "tenantKey",
                            "text",
                            "timestamp",
                            "uniqueId",
                            "url",
                            "userType",
                            "gender",
                            "income",
                            "marks",
                            "marksOrAb",
                            "valuationType",
                            "internalMarks"
                        ]
                    },
                    "defaultValue": {
                        "type": "string"
                    },
                    "dbColumnName": {
                        "type": "string"
                    },
                    "fieldType": {
                        "type": "string",
                        "enum": [
                            "generatedPrimaryKey",
                            "primaryKey",
                            "tenantKey",
                            "createdBy",
                            "createdAt",
                            "modifiedBy",
                            "modifiedAt",
                            "requiredData",
                            "optionalData"
                        ]
                    },
                    "label": {
                        "type": "string"
                    },
                    "icon": {
                        "type": "string"
                    },
                    "fieldPrefix": {
                        "type": "string"
                    },
                    "fieldSuffix": {
                        "type": "string"
                    },
                    "hint": {
                        "type": "string"
                    },
                    "placeHolder": {
                        "type": "string"
                    },
                    "listName": {
                        "type": "string"
                    },
                    "listKey": {
                        "type": "string"
                    },
                    "errorId":{
                        "type": "string"
                    },
                    "renderInList":{
                        "type": "boolean"
                    },
                    "renderInSave":{
                        "type": "boolean"
                    }
                },
                "additionalProperties": false
            }
        },
        "fromToPairs": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "field1",
                    "field2"
                ],
                "properties": {
                    "field1": {
                        "type": "string"
                    },
                    "field2": {
                        "type": "string"
                    },
                    "equalOk": {
                        "type": "boolean"
                    },
                    "errorId": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        },
        "inclusivePairs": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "field1",
                    "field2"
                ],
                "properties": {
                    "field1": {
                        "type": "string"
                    },
                    "field2": {
                        "type": "string"
                    },
                    "value1": {
                        "type": "string"
                    },
                    "errorId": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        },
        "exclusivePairs": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "field1",
                    "field2"
                ],
                "properties": {
                    "field1": {
                        "type": "string"
                    },
                    "field2": {
                        "type": "string"
                    },
                    "isRequired": {
                        "type": "boolean"
                    },
                    "errorId": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        }
    }
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/rec/user.rec.json
{
    "name": "user",
    "nameInDb": "users",
    "operations":["get", "filter", "create", "update"],
    "fields": [
        {
            "name": "userId",
            "dataType": "flexibleId",
            "dbColumnName": "user_id",
            "fieldType": "generatedPrimaryKey"
        },
        {
            "name": "instituteId",
            "dataType": "tenantKey",
            "dbColumnName": "institute_id",
            "fieldType": "tenantKey"
        },
        {
            "name": "trustId",
            "dataType": "id",
            "dbColumnName": "trust_id",
            "fieldType": "optionalData"
        },
        {
            "name": "userType",
            "dataType": "userType",
            "dbColumnName": "user_type",
            "fieldType": "requiredData",
            "defaultValue": "Student",
            "listName": "userType"
        },
        {
            "name": "loginId",
            "dataType": "loginId",
            "dbColumnName": "login_id",
            "fieldType": "requiredData"
        },
        {
            "name": "password",
            "dataType": "text",
            "dbColumnName": "password",
            "fieldType": "optionalData"
        },
        {
            "name": "loginEnabled",
            "dataType": "bool",
            "dbColumnName": "login_enabled",
            "fieldType": "requiredData",
            "defaultValue": "false"
        },
        {
            "name": "previousLoginAt",
            "dataType": "timestamp",
            "dbColumnName": "previous_login_at",
            "fieldType": "optionalData"
        },
        {
            "name": "currentLoginAt",
            "dataType": "timestamp",
            "dbColumnName": "current_login_at",
            "fieldType": "optionalData"
        },
        {
            "name": "resetPasswordCount",
            "dataType": "integer",
            "dbColumnName": "reset_password_count",
            "fieldType": "optionalData"
        },
        {
            "name": "resetPasswordSentAt",
            "dataType": "timestamp",
            "dbColumnName": "reset_password_sent_at",
            "fieldType": "optionalData"
        },
        {
            "name": "currentLoginIp",
            "dataType": "ip",
            "dbColumnName": "current_login_ip",
            "fieldType": "optionalData"
        },
        {
            "name": "previousLoginIp",
            "dataType": "ip",
            "dbColumnName": "previous_login_ip",
            "fieldType": "optionalData"
        },
        {
            "name": "loginCount",
            "dataType": "integer",
            "dbColumnName": "login_count",
            "fieldType": "optionalData"
        },
        {
            "name": "confirmationToken",
            "dataType": "text",
            "dbColumnName": "confirmation_token",
            "fieldType": "optionalData"
        },
        {
            "name": "loginToken",
            "dataType": "text",
            "dbColumnName": "login_token",
            "fieldType": "optionalData"
        },
        {
            "name": "isActive",
            "dataType": "bool",
            "dbColumnName": "is_active",
            "fieldType": "optionalData",
            "defaultValue": "true"
        },
        {
            "name": "createdAt",
            "dataType": "timestamp",
            "dbColumnName": "created_at",
            "fieldType": "createdAt"
        },
        {
            "name": "updatedAt",
            "dataType": "timestamp",
            "dbColumnName": "updated_at",
            "fieldType": "modifiedAt"
        }
    ]
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/rec/userContext.rec.json
{
    "name": "userContext",
    "nameInDb": "users",
    "useTimestampCheck": false,
    "fields": [
        {
            "name": "userId",
            "dataType": "flexibleId",
            "dbColumnName": "user_id",
            "fieldType": "primaryKey"
        },
        {
            "name": "instituteId",
            "dataType": "tenantKey",
            "dbColumnName": "institute_id",
            "fieldType": "tenantKey"
        },
        {
            "name": "trustId",
            "dataType": "id",
            "dbColumnName": "trust_id",
            "fieldType": "optionalData"
        },
        {
            "name": "userType",
            "dataType": "userType",
            "dbColumnName": "user_type",
            "fieldType": "requiredData",
            "defaultValue": "Student",
            "listName": "userType"
        },
        {
            "name": "loginId",
            "dataType": "loginId",
            "dbColumnName": "login_id",
            "fieldType": "requiredData"
        },
        {
            "name": "name",
            "dataType": "text",
            "fieldType": "optionalData"
        },
        {
            "name": "phoneNumber",
            "dataType": "text",
            "fieldType": "optionalData"
        },
        {
            "name": "email",
            "dataType": "text",
            "fieldType": "optionalData"
        },
        {
            "name": "designationId",
            "dataType": "id",
            "fieldType": "optionalData"
        },
        {
            "name": "designation",
            "dataType": "text",
            "fieldType": "optionalData"
        },
        {
            "name": "allowedPages",
            "dataType": "text",
            "fieldType": "optionalData"
        }
    ]
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/rec/returns.rec.json
{
    "name": "returns",
    "nameInDb": "returns",
    "operations":["create","update","filter","get"],
    "fields": [
        {
            "name": "returnId",
            "dataType": "flexibleId",
            "dbColumnName": "return_id",
            "fieldType": "generatedPrimaryKey"
        },
        {
            "name": "returnNumber",
            "dataType": "integer",
            "dbColumnName": "return_number",
            "fieldType": "requiredData"
        },
        {
            "name": "returnName",
            "dataType": "name",
            "dbColumnName": "return_name",
            "fieldType": "optionalData"
        }
    ]
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/rec/student.rec.json
{
    "name": "student",
    "nameInDb": "students",
    "operations":["create","update","filter","get"],
    "fields": [
        {
            "name": "studentId",
            "dataType": "flexibleId",
            "dbColumnName": "student_id",
            "fieldType": "generatedPrimaryKey"
        },
        {
            "name": "name",
            "dataType": "name",
            "dbColumnName": "name",
            "fieldType": "requiredData"
        },
        {
            "name": "email",
            "dataType": "email",
            "dbColumnName": "email",
            "fieldType": "requiredData"
        }
    ]
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/rec/tenentConfiguration.rec.json
{
    "name": "tenentConfiguration",
    "nameInDb": "tenent_configurations",
    "useTimestampCheck": false,
    "operations": [
        "get",
        "create",
        "update",
        "filter",
        "delete"
    ],
    "fields": [
        {
            "name": "tenentId",
            "dataType": "id",
            "dbColumnName": "tenent_id",
            "fieldType": "primaryKey",
            "label": "Tenents"
        },
        {
             "name": "currentSeason",
             "dataType": "id",
             "dbColumnName": "current_season",
             "fieldType": "requiredData"
         }

    ]
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/rec/employee.rec.json
{
    "name": "employee",
    "nameInDb": "employees",
    "operations":["create","update","filter","get"],
    "fields": [
        {
            "name": "employeeId",
            "dataType": "flexibleId",
            "dbColumnName": "employee_id",
            "fieldType": "generatedPrimaryKey"
        },
        {
            "name": "name",
            "dataType": "name",
            "dbColumnName": "name",
            "fieldType": "requiredData"
        },
        {
            "name": "email",
            "dataType": "email",
            "dbColumnName": "email",
            "fieldType": "requiredData"
        },
        {
            "name": "gender",
            "dataType": "text",
            "dbColumnName": "gender",
            "fieldType": "requiredData",
            "listName":"gender"
        },
        {
            "name": "phone",
            "dataType": "phone",
            "dbColumnName": "phone_number",
            "fieldType": "optionalData"
        }
    ]
}

=== supreethavadhani/Java-metadev-server-example/assets/spec/rec/order.rec.json
{
    "name": "order",
    "nameInDb": "orders",
    "operations":["create","update","filter","get"],
    "fields": [
        {
            "name": "orderId",
            "dataType": "flexibleId",
            "dbColumnName": "order_id",
            "fieldType": "generatedPrimaryKey"
        },
        {
            "name": "number",
            "dataType": "integer",
            "dbColumnName": "order_number",
            "fieldType": "requiredData"
        },
        {
            "name": "orderName",
            "dataType": "name",
            "dbColumnName": "order_name",
            "fieldType": "optionalData"
        }
    ]
}
